version: '2'

services:

  app:
    image: busybox
    volumes:
      - ./mount:/var/www


  # Nginx configuration
  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - "php:php-upstream"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from: 
      - app


  php:
    build: php
    volumes_from: 
      - app

volumes:
  mount: